name: Sebastian Scaparro - Doers Dream
favicon: null
layout_spectrum: 0.6469084520358592
typography_spectrum: 0.8151173291262239
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6717446749098599
  lightness: 0.8897341939155012
  saturation: 0.1273183492012322
  rhythmicContrast: 0.47548957518301904
purpose: []
